CREATE DATABASE MED_PAC;

USE MED_PAC;

CREATE TABLE AMBULATORIO (
	NrAmbul VARCHAR(3),
	NrAndar CHAR(4),
	Capacidade NUMERIC(6)
);

CREATE TABLE MEDICO (
	CRM VARCHAR(6) PRIMARY KEY,
	RgMedico VARCHAR(12) NOT NULL,
	NmMedico VARCHAR(50) NOT NULL,
	Idade NUMERIC(6) NOT NULL,
	Cidade VARCHAR(50),
	Especialidade VARCHAR(50)
	NrAmbul VARCHAR(3) REFERENCES AMBULATORIO
	);
	
CREATE TABLE PACIENTE (
	RGPaciente VARCHAR(12) PRIMARY KEY,
	NmPaciente VARCHAR(100),
	Sexo CHAR(1),
	Idade CHAR(3) NOT NULL,
	Cidade VARCHAR(30),
	Doenca VARCHAR(20)
);

CREATE TABLE CONSULTA (
	CRM VARCHAR(6) REFERENCES MEDICO,
	RGPaciente NUMERIC(10) REFERENCES PACIENTE,
	Data_Hora DATETIME,
	PRIMARY KEY (CRM, RGPaciente)
);
	
	INSERT INTO AMBULATORIO(01, 1, 50);
	INSERT INTO AMBULATORIO(02, 2, 40);
	INSERT INTO AMBULATORIO(03, 3, 40);
	INSERT INTO AMBULATORIO(04, 4, 10);
	INSERT INTO AMBULATORIO(05, 5, 100);

	INSERT INTO MEDICO('111111',11111111111,'JOÃO PEDRO', 45, 'SOROCABA', 'CARIDOLOGISTA','01');
	INSERT INTO MEDICO('222222',22222222222,'MARIA DE MORAIS', 30, 'ITU', 'Dermatologia','02');
	INSERT INTO MEDICO('333333',33333333333,'PEDRO GARCIA', 50, 'SALTO', 'Neurologia','03');
	INSERT INTO MEDICO('444444',44444444444,'JOANA SANTOS', 26, 'PORTO FELIZ', 'pediatria','04');
	INSERT INTO MEDICO('555555',55555555555,'PAULA DA SILVA', 60, 'SÃO PAULO', 'Oftalmologia','05');

	INSERT INTO PACIENTE(11111111112, 'ROGERINHO','M', '16','SOROCABA','SARAMPO' );
	INSERT INTO PACIENTE(11111111113, 'SANDRA','F', '25','ITU','RubEola' );
	INSERT INTO PACIENTE(11111111114, 'LEONARDO','M', '35','SALTO','DENGUE' );
	INSERT INTO PACIENTE(11111111115, 'PEDRO','M', '40','SOROCABA','VIROSE' );

	INSERT INTO CONSULTA('111111',11111111112,'21-09-2020');
	INSERT INTO CONSULTA('222222',11111111113,'21-11-2020');
	INSERT INTO CONSULTA('333333',11111111114,'20-11-2020');
	INSERT INTO CONSULTA('444444',11111111115,'30-10-2020');
	INSERT INTO CONSULTA('555555',11111111113,'26-10-2020');

	SELECT * FROM MEDICO;
	SELECT * FROM PACIENTE;
	SELECT * FROM AMBULATORIO;
	SELECT * FROM CONSULTA;

DROP TABLE MEDICO;

ALTER TABLE CONSULTA ADD VrConsulta MONEY CHECK(VrConsulta > 0);
ALTER TABLE MEDICO ALTER COLUMN NrMedico VARCHAR(100);
UPDATE CONSULTA SET SELECT VrConsulta * 0,05 + VrConsulta FROM CONSULTA; 
DELETE FROM CONSULTA WHEN Data_Hora = CONVERT (date, GETDATE());

SELECT * FROM MEDICO;
SELECT * FROM PACIENTE;
SELECT * FROM AMBULATORIO;
SELECT * FROM CONSULTA;

SELECT NmMedico FROM MEDICO WHERE Cidade = 'itu'
SELECT NmPaciente FROM PACIENTE WHERE NmPaciente LIKE 'R%';

SELECT * FROM PACIENTE  where IDADE BETWEEN 10 AND 30;
SELECT CRM FROM MEDICO ORDER BY Especialidade ASC

SELECT * FROM PACIENTE WHERE Cidade = 'SOROCABA' OR Doenca = 'VIROSE';
SELECT NmMedico FROM MEDICO where Especialidade = 'OFTAMOLOGIA' AND IDADE BETWEEN 25 AND 55;
SELECT NmMedico, NrAmbul FROM MEDICO

SELECT NrAmbul FROM AMBULATORIO WHERE NOT IN (2,4) AND Capacidade > 50;
SELECT * FROM CONSULTA WHERE CRM NOT IN(46,79);
SELECT NmMedico, Especialidade FROM MEDICO;

SELECT * FROM AMBULATORIO WHERE ANDAR = 4 AND Capacidade > 10 AND  Capacidade =50;

SELECT RGPaciente FROM PACIENTE WHERE Data_Hora = CONVERT (date, GETDATE())

 SELECT  FROM PACIENTE WHERE Doenca = 'sarampo';
SELECT DISTINCT Doenca FROM PACIENTE;

SELECT NmPaciente, Idade FROM PACIENTE order by NmPaciente, Cidade
SELECT NmPaciente FROM PACIENTE WHERE Idade >15 AND (Cidade = 'itu' OR Cidade = 'Salto') AND Doenca = 'Rubéola';

SELECT (VrConsulta *0,1 + VrConsulta) AS VALOR_ACRES FROM CONSULTA WHERE CRM ='111222' AND MOUNT(Data_hora) = '04' AND YEAR(Data_Hora) = '2016';
SELECT * FROM tabela WHERE DAY(data) = 'dia_escolhido'
SELECT * FROM tabela WHERE MONTH(data) = 'mes_escolhido'
SELECT * FROM tabela WHERE YEAR(data) = 'ano_escolhido'

SELECT NmMedico FROM MEDICO WHERE Especialidade = '%IA';
SELECT * FROM PACIENTE WHERE Cidade = 'SOROCABA';
SELECT CRM FROM MEDICO WHERE NmMedico = 'M%' AND Idade > 40 AND Cidade = 'Itu' OR NrAmbul = 10 AND Especialidade = 'cardiologista';


--parte 3

SELECT NrAmbul, Capacidade, NmMedico FROM AMBULATORIO A, MEDICO M where A.ANDAR = 5 AND A.CRM = M.CRM;
SELECT NmMedico FROM CONSULTA C, MEDICO M WHERE M.CRM = C.CRM AND C.Data_hora BETWEEN '20030415 07:00' AND '20030415 12:00';
SELECT * FROM MEDICO WHERE Especialidade = 'ortopedista' AND Idade > 55;
SELECT CRM FROM CONSULTA WHERE RGPaciente = '122' AND RGPaciente = '725';
SELECT CRM FROM CONSULTA WHERE VrConsulta > 150,00;
SELECT NmMedico, NmPaciente, Data_Hora, VrConsulta FROM CONSULTA C, MEDICO M, PACIENTE P WHERE P.RGPaciente = C.RGPaciente AND M.CRM = C.CRM;
SELECT * FROM AMBULATORIO A, MEDICO M WHERE M.CRM = A.CRM;
SELECT NmMedico,NmPaciente, Data_Hora FROM CONSULTA;
SELECT NmMedico FROM CONSULTA C, MEDICO M WHERE M.CRM = C.CRM; 
SELECT NmMedico FROM CONSULTA WHERE CRM IN (SELECT CRM FROM MEDICO);

SELECT NmPaciente FROM CONSULTA C, MEDICO M, PACIENTE P WHERE P.RGPaciente = C.RGPaciente AND C.CRM = M.CRM AND NmMedico IN ('MARIA', 'JOÃO') AND P.Doenca = 'pneumonia';

SELECT Andar from AMBULATORIO, PACIENTE WHERE NmPaciente = 'José' AND Doenca = 'dengue';
SELECT COUNT(Especialidade) FROM MEDICO;
SELECT COUNT(CRM) FROM AMBULATORIO WHERE GROUP BY Andar;
SELECT AVG(VrConsulta), NmMedico from CONSULTA C, MEDICO M WHERE M.CRM = C.CRM GROUP BY NmMedico;
SELECT NmPaciente SUM(VrConsulta)> 600 from CONSULTA, PACIENTE WHERE P.RGPaciente = C.RGPaciente AND SUM(VrConsulta) GROUP BY PACIENTE ;

CREATE VIEW consulta_medico_paciente_INNER
AS
SELECT
M.NmMedico, 
M.idade, 
M.Especialidade
C.Data_hora 
P.NmPaciente
P.Cidade,
P.Idade
FROM
MEDICO M INNER JOIN CONSULTA C ON M.CRM = C.CRM INNER JOIN PACIENTE P ON C.RgPaciente = P.RgPaciente;

SELECT * FROM consulta_medico_paciente_INNER

CREATE VIEW consulta_medico_paciente
AS
SELECT
M.NmMedico, 
M.idade, 
M.Especialidade
C.Data_hora 
P.NmPaciente
P.Cidade,
P.Idade
FROM MEDICO M, CONSULTA C, PACIENTE P WHERE M.CRM = C.CRM AND C.RgPaciente = P.RgPaciente;

SELECT * FROM consulta_medico_paciente

CREATE PROC inserir_ambulatorio @NrAmbul VARCHAR(3), @NrAndar CHAR(4),@Capacidade NUMERIC(6)
AS
	INSERT INTO AMBULATORIO VALUES (@NrAmbul, @NrAndar,@Capacidade)
EXEC inserir_ambulatorio '01','05','100'

CREATE PROC SELECIONA_CONSULTA_PACIENTES @rgpaciente NUMERIC(12)
AS
SELECT P.NmPaciente, C.Data_hora FROM PACIENTE P, CONSULTA C WHERE P.rgPaciente = @rgpaciente and C.RgPaciente = @rgpaciente
SELECIONA_CONSULTA_PACIENTES '0125354'