DECLARE @SALARIO NUMERIC(5,2), @PERCENTUAL NUMERIC(5,2);

BEGIN 
SELECT @SALARIO = 800.00, @PERCENTUAL = 0.10;

SELECT @SALARIO = (@SALARIO * @PERCENTUAL) + @SALARIO;
PRINT @SALARIO;

END;


--EX1
CREATE DATABASE EXERC
USE EXERC;


DECLARE @NOME VARCHAR(10)
SET @NOME = 'GABRIELE'
PRINT @NOME;


--EX2
DECLARE @NOME VARCHAR(10), @SOBRENOME VARCHAR(10);
SELECT @NOME = 'GABRIELE', @SOBRENOME = 'KATHERINE';
PRINT @NOME + space(1) + @SOBRENOME;

--ex3
DECLARE @A int, @B int, @C real, @D real;
BEGIN
SELECT @A = 10, @B = 25, @C = 15, 
@D = 5.5,
@A = @B * @C,
@C = (@D * @B) + @C,
@B= (@B*@B) + 18000,
@A = @A - @A;
 PRINT (' VALOR DE A' + str(@A ))
 PRINT (' VALOR DE B' + str(@B ))
 PRINT (' VALOR DE C' + str(@C ))
 PRINT (' VALOR DE D' + str(@D ))
 END;

 --ex4
 CREATE TABLE CARGO(
	CdCargo NUMERIC(3) NOT NULL PRIMARY KEY,
	NmCargo VARCHAR(10));

 CREATE TABLE DEPTO(
	CdDepto NUMERIC (3) NOT NULL PRIMARY KEY,
	NmDepto VARCHAR(10) NOT NULL);

  CREATE TABLE FUNCIONARIO(
  CdFunc NUMERIC(05) PRIMARY KEY,
  NmFunc VARCHAR(30) NOT NULL,
  Endereco VARCHAR(25) NOT NULL,
  Telefone VARCHAR(20) NOT NULL,
  DtNascimento DATETIME NOT NULL,
  DtAdimissão DATETIME not null,
  VrSalario NUMERIC(8,2) NOT NULL,
  CdDepto NUMERIC(3) NOT NULL REFERENCES DEPTO,
  CdCargo NUMERIC(3) NOT NULL REFERENCES CARGO);

  SELECT * FROM DEPTO
  SELECT * FROM FUNCIONARIO
  SELECT * FROM CARGO
  --DROP TABLE FUNCIONARIO
  INSERT INTO CARGO VALUES (01,'TI');
  INSERT INTO CARGO VALUES (02,'VENDEDOR');

  INSERT INTO DEPTO VALUES (01,'TI DEPTO');
  INSERT INTO DEPTO VALUES (02,'VENDAS');

  INSERT INTO FUNCIONARIO VALUES (01,'MARIA','RUA A', '123', '12-10-1980', '12-5-2012', 1530.80, 01,01);
  INSERT INTO FUNCIONARIO VALUES (02,'JOAO','RUA B', '456', '14-9-1990', '12-05-2010', 1000.80, 02,02 );

  --EX4
  DECLARE   @NmFun VARCHAR(10),@DtAdimis DATE, @SALARIO NUMERIC(8,2)
  BEGIN
  SELECT @NmFun = NmFunc, @DtAdimis = DtAdimissão, @SALARIO = VrSalario FROM FUNCIONARIO WHERE CdFunc = 01
  PRINT  @NmFun
  PRINT  @DtAdimiS
  PRINT  @SALARIO
  END;

  --EX5
  DECLARE @nmdepto VARCHAR(10)
  select @nmdepto = NmDepto from DEPTO WHERE CdDepto = 01 
  PRINT @nmdepto

  --exercicio aula

  CREATE PROC AUMENTO_FUNC @NOME_D VARCHAR(20), @PERC INT AS 
  SELECT NmFunc, VrSalario,(VrSalario + (VrSalario * @PERC/100))
  FROM FUNCIONARIO, DEPTO
  WHERE FUNCIONARIO.CdDepto = DEPTO.CdDepto
  and NmDepto = @NOME_D;

  EXEC AUMENTO_FUNC 'TI', '10'