CREATE DATABASE BD_FUNC

USE BD_FUNC

CREATE TABLE Cargos
  (CdCargo	 CHAR(05) 		PRIMARY KEY,
   NmCargo	 VARCHAR(50)	NOT NULL,
   VrSalario NUMERIC (6,2)	CHECK (VrSalario > 0) );

CREATE TABLE Deptos
  (CdDepto	CHAR(03) 		PRIMARY KEY,
   NmDepto	VARCHAR(50)		NOT NULL,
   Ramal 	NUMERIC (6) );
    
CREATE TABLE Funcionarios
  (NrMatric	INT				PRIMARY KEY IDENTITY,
   NmFunc	VARCHAR(50)		NOT NULL,
   Sobrenome  VARCHAR(100)	NOT NULL, 
   Sexo		CHAR(01)		CHECK (Sexo IN ('F', 'M')),
   DtAdm	DATETIME,
   CdDepto	CHAR(03)		NOT NULL REFERENCES Deptos,
   CdCargo	CHAR(05)		REFERENCES Cargos,
   UNIQUE (NmFunc, Sobrenome));

INSERT INTO Deptos VALUES ('D01', 'ADMINISTRATIVO', 100);
INSERT INTO Deptos VALUES ('D02', 'COMERCIAL', 120);
INSERT INTO Deptos VALUES ('D03', 'INFORMATICA', 130);   

SELECT * FROM Deptos; 

INSERT INTO Cargos VALUES ('C10', 'GERENTE', 8500);
INSERT INTO Cargos VALUES ('C11', 'DIRETOR DE VENDAS', 7000);
INSERT INTO CArgos VALUES ('C12', 'ANALISTA DE SISTEMAS', 5250); 

SELECT * FROM Cargos; 

INSERT INTO Funcionarios VALUES ('JOAO', 'NOGUEIRA', 'M', '05-12-2001', 'D03', 
'C12');
INSERT INTO Funcionarios VALUES ('JOAO', 'SAMPAIO', 'M', '02-10-2003', 'D01', 
'C10');
INSERT INTO Funcionarios VALUES ('MARIA', 'SOARES', 'F', '13-02-2000', 'D02', 
'C11');
INSERT INTO Funcionarios VALUES ('ROBERTO', 'PEREIRA', 'M', '22-05-2009', 'D01', 
'C10');
INSERT INTO Funcionarios VALUES ('RUTE', 'SOUZA', 'F', '30-04-1999', 'D01',
'C10');
INSERT INTO Funcionarios VALUES ('REGINA', 'SIMOES', 'F', '01-12-2007', 'D03',
'C12');
INSERT INTO Funcionarios VALUES ('ALVARO', 'SAMPAIO', 'M', '13-11-1998', 'D03',
'C12');

-- MOSTRAR OS DADOS DE TODOS OS FUNCIONÁRIOS CADASTRADOS
SELECT * FROM Funcionarios

-- MOSTRAR O NOME, O SOBRENOME E A DATA DE ADMISSÃO DE TODOS OS 
--FUNCIONÁRIOS
SELECT NMFUNC, SOBRENOME, DTADM FROM Funcionarios

-- MOSTRAR TODOS OS SOBRENOMES DOS FUNCIONÁRIOS, SEM REPETIÇÃO.
SELECT DISTINCT SOBRENOME FROM Funcionarios

--MOSTRAR O NUM. MATRICULA, O NOME E O SEXO DE TODOS OS FUNCIONARIOS,
--ORDENANDO O RESULTADO POR NOME DO FUNCIONARIO
SELECT NrMatric, NmFunc, Sexo FROM FUNCIONARIOS
ORDER BY NmFunc

--MOSTRAR O NOME E A DATA DE ADMISSÃO DOS FUNCIONARIOS, POR ORDEM 
--DECRESCENTE DE DATA DE ADMISSÃO
SELECT NMFUNC, DTADM FROM Funcionarios
ORDER BY DtAdm DESC

--MOSTRAR O NOME, O SOBRENOME E O SEXO DE TODOS OS FUNCIONARIOS,
--ORDENANDO O RESULTADO POR NOME E SOBRENOME
SELECT NMFUNC, SOBRENOME, SEXO FROM Funcionarios
ORDER BY NmFunc, Sobrenome

--MOSTRAR TODOS OS FUNCIONARIOS QUE PERTENCEM AO DEPTO DE COD. D02
SELECT * FROM Funcionarios
WHERE CdDepto = 'D02'

--MOSTRAR O NOME DOS CARGOS CUJO VALOR DO SALARIO É MAIOR OU IGUAL
--A R$ 6000,00
SELECT NMCARGO FROM Cargos
WHERE VrSalario >= 6000 

--MOSTRAR O NOME DOS CARGOS, O VALOR DO SALARIO CADASTRADO E O 
--VALOR DO SALARIO COM 5% DE ACRESCIMO
SELECT NMCARGO, VRSALARIO, VRSALARIO * 1.05 AS VR_SAL_COM_ACRESCIMO
FROM CARGOS

--MOSTRAR O NUM. MATRICULA DOS FUNCIOANARIOS QUE POSSUEM CARGO
--DIFERENTE DE C10
SELECT NRMATRIC FROM Funcionarios
WHERE CdCargo <> 'C10'

--MOSTRAR TODOS OS FUNCIONAROS QUE POSSUEM SOBRENOME 'NOGUEIRA' OU
--'SAMPAIO'
SELECT * FROM Funcionarios
WHERE Sobrenome = 'NOGUEIRA' OR Sobrenome = 'SAMPAIO'

SELECT * FROM Funcionarios
WHERE Sobrenome IN ('NOGUEIRA', 'SAMPAIO')

--MOSTRAR O NOME E A DATA DE ADMISSÃO DOS FUNCIONARIOS ADMITIDOS
--ENTRE 2000 E 2001
SELECT NMFUNC, DTADM FROM Funcionarios
WHERE DtAdm >= '01-01-2000' AND DtAdm <= '31-12-2001'

SELECT NMFUNC, DTADM FROM Funcionarios
WHERE DtAdm BETWEEN '01-01-2000' AND '31-12-2001'

--MOSTRAR TODOS OS FUNCIONARIOS CUJO NOME COMEÇA COM A LETRA 'R'
SELECT * FROM Funcionarios
WHERE NmFunc LIKE 'R%'

--MOSTRAR O NOME, O SOBRENOME, A DATA DE ADMISSÃO E O COD. DEPTO
--DE TODOS OS FUNCIONARIOS DO SEXO FEMININO, QUE POSSUEM SOBRENOME 
--SOUZA OU CARGO IGUAL A C10 E QUE FORAM ADMITIDOS NO ANO DE 2009
SELECT NMFUNC, SOBRENOME, DTADM, CDDEPTO
FROM Funcionarios
WHERE Sexo = 'F'
AND (Sobrenome = 'SOUZA' OR CdCargo = 'C10')
AND DtAdm BETWEEN '01-01-2009' AND '31-12-2009'

--MOSTRAR O NOME DOS FUNCIONARIOS QUE POSSUEM CARGO ANALISTA DE SISTEMAS
SELECT NMFUNC
FROM Funcionarios F, Cargos C
WHERE F.CdCargo = C.CdCargo
AND NmCargo = 'ANALISTA DE SISTEMAS'

--MOSTRAR O NOME, A DATA DE ADMISSÃO E O VALOR DO SALARIO DE TODOS DTADM
--OS FUNCIONARIOS
SELECT NMFUNC, DTADM, VRSALARIO
FROM Funcionarios F, Cargos C
WHERE F.CdCargo = C.CdCargo 

--MOSTRAR O NUM. MATRICULA, O COD. DEPTO, O NOME E O SOBRENOME DE TODOS 
--OS FUNCIONARIOS QUE PERTENCEM AO DEPTO COMERCIAL
SELECT NRMATRIC, F.CDDEPTO, NMFUNC, SOBRENOME
FROM Funcionarios F, Deptos D
WHERE F.CdDepto = D.CdDepto
AND NmDepto = 'COMERCIAL'

--MOSTRAR O NOME DOS FUNCIONARIOS QUE SÃO GERENTES E FORAM ADMITIDOS 
--ANTES DE 2002.
SELECT NMFUNC
FROM Funcionarios F, Cargos C
WHERE F.CdCargo = C.CdCargo
AND NmCargo = 'GERENTE'
AND DtAdm < '01-01-2002'

--MOSTRAR O NUM. MATRICULA, O NOME E O SOBRENOME DOS FUNCIONARIOS DO 
--SEXO MASCULINO, QUE SÃO ANALISTAS DE SISTEMAS E PERTENCEM AO DEPTO 
--INFORMATICA. MOSTRAR O RESULTADO POR ORDEM DECRESCENTE DE NOME.
SELECT NRMATRIC, NMFUNC, SOBRENOME
FROM Cargos C, Funcionarios F, Deptos D
WHERE C.CdCargo = F.CdCargo
AND F.CdDepto = D.CdDepto
AND SEXO = 'M'
AND NmCargo = 'ANALISTA DE SISTEMAS'
AND NmDepto = 'INFORMATICA'
ORDER BY NmFunc DESC

-- *********************************************
alter table funcionarios
add vrsalario money

update Funcionarios
set vrsalario = (select vrsalario from Cargos where Funcionarios.CdCargo = 
                                        Cargos.CdCargo )
where CdCargo = CdCargo
-- *********************************************

--MOSTRAR QUANTOS FUNCIONARIOS EXISTEM CADASTRADOS
SELECT COUNT (*)
FROM Funcionarios

--MOSTRAR O VALOR MÍNIMO DOS SALARIOS CADASTRADOS PARA OS DIFERENTES CARGOS
--DA EMPRESA
SELECT MIN (VRSALARIO)
FROM CARGOS

--MOSTRAR O VALOR MÁXIMO DOS SALARIOS DOS FUNCIONÁRIOS, AGRUPADOS POR 
--COD. DO DEPARTAMENTO
SELECT CDDEPTO, MAX (VRSALARIO)
FROM Funcionarios
GROUP BY CdDepto

--MOSTRAR QUANTOS FUNCIONARIOS EXISTEM EM CADA DEPARTAMENTO. EXIBIR O
--NOME DO DEPARTAMENTO E A QUANTIDADE
SELECT NMDEPTO, COUNT (*)
FROM Deptos D, Funcionarios F
WHERE D. CdDepto = F.CdDepto
GROUP BY NMDEPTO

--MOSTRAR QUANTOS FUNCIONARIOS EXISTEM EM CADA DEPARTAMENTO. EXIBIR O
--COD., O NOME DO DEPARTAMENTO E A QUANTIDADE SOMENTE DOS DEPARTAMENTOS
--QUE POSSUEM MAIS DE 2 FUNCIONARIOS
SELECT D.CDDEPTO, NMDEPTO, COUNT (*)
FROM Deptos D, Funcionarios F
WHERE D.CdDepto = F.CdDepto
GROUP BY D.CdDepto, NmDepto
HAVING COUNT (*) > 2

--MOSTRAR A SOMA TOTAL DO VALOR DOS SALARIOS DOS FUNCIONARIOS DO SEXO 
--MASCULINO QUE OCUPAM CADA CARGO DA EMPRESA
SELECT CDCARGO, SUM (VRSALARIO)
FROM Funcionarios
WHERE Sexo = 'M'
GROUP BY CdCargo

--MOSTRAR QUANTOS FUNCIONARIOS DO SEXO MASCULINO OCUPAM CADA CARGO
--DA EMPRESA. EXIBIR SOMENTE O NOME DOS CARGOS CUJO VALOR TOTAL DOS SALARIOS
--SEJA MAIOR QUE 11000
SELECT NMCARGO, COUNT (*)
FROM Cargos C, Funcionarios F
WHERE C.CdCargo = F.CdCargo
AND Sexo = 'M'
GROUP BY NmCargo
HAVING SUM (F.VRSALARIO) > 11000
 

-- *********************************************
USE BD_FUNC

CREATE TABLE Projetos
(NrProj		INT		PRIMARY KEY IDENTITY,
 DsProj		VARCHAR(50))
 
CREATE TABLE Trabalha_em
(NrMatric	INT		REFERENCES Funcionarios,
 NrProj		INT		REFERENCES Projetos,
 PRIMARY KEY (NrMAtric, NrProj))
 
 INSERT INTO Projetos VALUES ('Projeto A')
 INSERT INTO Projetos VALUES ('Projeto B'
 
 INSERT INTO Trabalha_em VALUES (1, 1)
 INSERT INTO Trabalha_em VALUES (1, 2)
 INSERT INTO Trabalha_em VALUES (2, 2)
 INSERT INTO Trabalha_em VALUES (4, 1)
 INSERT INTO Trabalha_em VALUES (6, 2)
 INSERT INTO Trabalha_em VALUES (7, 1)
 INSERT INTO Trabalha_em VALUES (7, 2)
 -- *********************************************
 
--MOSTRAR O NOME E O SALARIO DOS FUNCIONARIOS QUE TRABALHAM NO
 --MESMO DEPARTAMENTO QUE 'JOAO NOGUEIRA' TRABALHA.
 SELECT NMFUNC, VRSALARIO
 FROM Funcionarios
 WHERE CdDepto = (SELECT CDDEPTO
				FROM Funcionarios
				WHERE NmFunc = 'JOAO' AND Sobrenome = 'NOGUEIRA')
AND NmFunc <> 'JOAO'

--MOSTRAR O NOME DOS FUNCIONARIOS QUE POSSUEM SALARIO MAIOR DO
--QUE A MÉDIA SALARIAL DA EMPRESA.
SELECT NMFUNC
FROM Funcionarios
WHERE vrsalario > (SELECT AVG(VRSALARIO) 
					FROM FUNCIONARIOS)

--MOSTRAR O NOME DOS CARGOS QUE POSSUEM A MESMA QUANTIDADE DE 
--FUNCIONARIOS QUE O CARGO 'GERENTE' POSSUI
SELECT NMCARGO, COUNT (*)
FROM Cargos C, FUNCIONARIOS F
WHERE C.CdCargo = F.CdCargo
AND NmCargo <> 'GERENTE'
GROUP BY NmCargo
HAVING COUNT (*) = (SELECT COUNT(*)
					FROM Funcionarios F, Cargos C
					WHERE F.CDCARGO = C.CDCARGO
					AND NmCargo = 'GERENTE')

--MOSTRAR O NOME DOS FUNCIONARIOS QUE PARTICIPARAM DOS MESMOS
--PROJETOS QUE O FUNCIONARIO 1 PARTICIPOU

SELECT NMFUNC, T.NrProj
FROM Funcionarios F, Trabalha_em T
WHERE F.NrMatric = T.NrMatric
AND NrProj IN (SELECT NRPROJ
			FROM Trabalha_em
			WHERE NrMatric = 1)
AND F.NrMatric <> 1

--MOSTRAR O NOME DE TODOS OS FUNCIONARIOS QUE FORAM ADMITIDOS ANTES 
--DO ANO 2000 OU QUE PERTENCEM AO DEPTO 'ADMINISTRATIVO' (USAR UNIÃO)

(SELECT NMFUNC
FROM Funcionarios
WHERE YEAR (DTADM) < '2000')
UNION
(SELECT NMFUNC
FROM FUNCIONARIOS F, Deptos D
WHERE F.CDDEPTO = D.CdDepto
AND NmDepto = 'ADMINISTRATIVO')

--MOSTRAR O NRMATRIC E A DTADM DOS FUNCIONARIOS QUE GANHAM MAIS
--DE R$ 6000,00 E QUE NÃO POSSUEM CARGO C10 (USAR INTERSECÇÃO)

(SELECT NRMATRIC, DTADM
FROM Funcionarios
WHERE vrsalario > 6000)
INTERSECT
(SELECT NRMATRIC, DTADM
FROM Funcionarios
WHERE CdCargo <> 'C10')

--MOSTRAR O NOME DOS FUNCIONARIOS QUE NÃO PARTICIPAM DE PROJETOS 
--(USAR DIFERENÇA DE CONJUNTOS)

(SELECT NRMATRIC, NmFunc FROM Funcionarios)
EXCEPT
(SELECT F.NRMATRIC, NMFUNC 
FROM FUNCIONARIOS F, Trabalha_em T
WHERE F.NrMatric = T.NrMatric)

--OU

SELECT NRMATRIC, NmFunc 
FROM Funcionarios
WHERE NRMATRIC NOT IN (SELECT F.NRMATRIC 
						FROM FUNCIONARIOS F, Trabalha_em T
						WHERE F.NrMatric = T.NrMatric)





SELECT * FROM DEPTOS























SELECT * FROM FUNCIONARIOS





SELECT * FROM FUNCIONARIOS









 
 
 
 
 
 
 
 
 
 
 
 












SELECT * FROM Funcionarios




































































