SELECT * FROM ANIMAL;

SELECT CODIGO_ANIMAL,NOME_ANIMAL,DATA_NASCIMENTO FROM ANIMAL;

SELECT CODIGO_ANIMAL, NOME_ANIMAL, NOME_DONO, DESCRICAO_RACA FROM ANIMAL, DONO, RACA WHERE ANIMAL.CODIGO_DONO = DONO.CODIGO_DONO AND ANIMAL.CODIGO_RACA = RACA.CODIGO_RACA;

SELECT NOME_ANIMAL, DESCRICAO_RACA FROM ANIMAL, RACA WHERE ANIMAL.CODIGO_RACA = RACA.CODIGO_RACA AND PESO > 12.00;

SELECT * FROM ANIMAL WHERE DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) > 10.00;

SELECT * FROM ANIMAL WHERE (DATA_NASCIMENTO < '2015-01-01' AND PESO > 10.00) OR CODIGO_RACA IN (SELECT CODIGO_RACA FROM RACA WHERE DESCRICAO_RACA='LABRADOR');

SELECT FLOOR(DATEDIFF(DAY,DATA_NASCIMENTO,GETDATE()) / 365.25) FROM ANIMAL;

SELECT NOME_DONO FROM ANIMAL, DONO WHERE ANIMAL.CODIGO_DONO = DONO.CODIGO_DONO AND NOME_DONO LIKE 'L%' AND CODIGO_RACA IN (SELECT CODIGO_RACA FROM RACA WHERE DESCRICAO_RACA='MALTÊS');

SELECT MEDICAMENTO.CODIGO_MEDICAMENTO, DESCRICAO_MEDICAMENTO, ANIMAL.CODIGO_ANIMAL, NOME_ANIMAL FROM ANIMAL, MEDICAMENTO, ANIMAL_MEDICAMENTO 
WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_MEDICAMENTO.CODIGO_ANIMAL AND MEDICAMENTO.CODIGO_MEDICAMENTO = ANIMAL_MEDICAMENTO.CODIGO_MEDICAMENTO
ORDER BY MEDICAMENTO.CODIGO_MEDICAMENTO;

SELECT NOME_ANIMAL, DESCRICAO_MEDICAMENTO FROM ANIMAL, MEDICAMENTO, ANIMAL_MEDICAMENTO
WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_MEDICAMENTO.CODIGO_ANIMAL AND MEDICAMENTO.CODIGO_MEDICAMENTO = ANIMAL_MEDICAMENTO.CODIGO_MEDICAMENTO
ORDER BY DESCRICAO_MEDICAMENTO DESC;

SELECT NOME_VETERINARIO, COUNT(*) FROM VETERINARIO WHERE CODIGO_VETERINARIO IN (SELECT CODIGO_VETERINARIO FROM ANIMAL_MEDICAMENTO WHERE DATEDIFF(MONTH,DATA_MEDICAMENTO,GETDATE()) = 1)
GROUP BY NOME_VETERINARIO;

SELECT NOME_ANIMAL, DATA_MEDICAMENTO FROM ANIMAL, ANIMAL_MEDICAMENTO WHERE DATA_MEDICAMENTO = GETDATE() AND ANIMAL.CODIGO_ANIMAL = ANIMAL_MEDICAMENTO.CODIGO_ANIMAL;

SELECT DESCRICAO_SERVICO, VALUNIT_SERVICO FROM SERVICO WHERE VALUNIT_SERVICO > (SELECT AVG(VALUNIT_SERVICO) FROM SERVICO);

SELECT NOME_VETERINARIO FROM VETERINARIO
ORDER BY NOME_VETERINARIO;

SELECT COUNT(*) FROM ANIMAL;
 
SELECT CODIGO_ANIMAL, (SELECT SUM(VALUNIT_SERVICO * QTDE_SERVICO) FROM SERVICO, ANIMAL_SERVICO WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_SERVICO.CODIGO_ANIMAL) FROM ANIMAL;

SELECT AVG((SELECT COUNT(*) FROM ANIMAL_MEDICAMENTO)) FROM ANIMAL_MEDICAMENTO;

SELECT * FROM ANIMAL WHERE CODIGO_ANIMAL IN (SELECT CODIGO_ANIMAL FROM ANIMAL_SERVICO,SERVICO WHERE SERVICO.CODIGO_SERVICO = ANIMAL_SERVICO.CODIGO_SERVICO AND DESCRICAO_SERVICO = 'VACINAÇÃO') OR CODIGO_ANIMAL IN (SELECT CODIGO_ANIMAL FROM ANIMAL_MEDICAMENTO,MEDICAMENTO WHERE MEDICAMENTO.CODIGO_MEDICAMENTO = ANIMAL_MEDICAMENTO.CODIGO_MEDICAMENTO AND DESCRICAO_MEDICAMENTO = 'IVOMEC');

--
SELECT NOME_ANIMAL, PESO, DESCRICAO_RACA FROM ANIMAL, RACA WHERE ANIMAL.CODIGO_RACA = RACA.CODIGO_RACA
ORDER BY DESCRICAO_RACA, NOME_ANIMAL;

SELECT CODIGO_SERVICO, CODIGO_MEDICAMENTO FROM ANIMAL_MEDICAMENTO, ANIMAL_SERVICO WHERE ANIMAL_MEDICAMENTO.CODIGO_ANIMAL = 'AN005' AND ANIMAL_SERVICO.CODIGO_ANIMAL = 'AN005';

SELECT NOME_ANIMAL,COUNT(QTDE_MEDICAM) AS QTD_MED FROM ANIMAL, ANIMAL_MEDICAMENTO WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_MEDICAMENTO.CODIGO_ANIMAL
GROUP BY ANIMAL.NOME_ANIMAL
HAVING COUNT(QTDE_MEDICAM) > 1;

SELECT COUNT(QTDE_MEDICAM) AS QTD_MED FROM ANIMAL_MEDICAMENTO, ANIMAL, VETERINARIO
WHERE (ANIMAL_MEDICAMENTO.CODIGO_ANIMAL = ANIMAL.CODIGO_ANIMAL AND ANIMAL.NOME_ANIMAL = 'THOR') AND (ANIMAL_MEDICAMENTO.CODIGO_VETERINARIO = VETERINARIO.CODIGO_VETERINARIO AND VETERINARIO.NOME_VETERINARIO = 'DR. FRANCISCO MARTINS');

SELECT CODIGO_SERVICO, DESCRICAO_SERVICO FROM SERVICO WHERE VALUNIT_SERVICO > 50;

SELECT NOME_ANIMAL, NOME_VETERINARIO, DESCRICAO_MEDICAMENTO FROM ANIMAL, ANIMAL_MEDICAMENTO, MEDICAMENTO, VETERINARIO
WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_MEDICAMENTO.CODIGO_ANIMAL AND VETERINARIO.CODIGO_VETERINARIO = ANIMAL_MEDICAMENTO.CODIGO_VETERINARIO AND MEDICAMENTO.CODIGO_MEDICAMENTO = ANIMAL_MEDICAMENTO.CODIGO_MEDICAMENTO
ORDER BY NOME_ANIMAL;

SELECT CODIGO_ANIMAL, NOME_ANIMAL FROM ANIMAL WHERE CODIGO_RACA IN (SELECT CODIGO_RACA FROM ANIMAL WHERE NOME_ANIMAL = 'BOOMER');

SELECT NOME_DONO, DESCRICAO_RACA FROM ANIMAL, RACA, DONO WHERE DONO.CODIGO_DONO = ANIMAL.CODIGO_DONO AND RACA.CODIGO_RACA = ANIMAL.CODIGO_RACA
GROUP BY DESCRICAO_RACA, NOME_DONO;

(SELECT * FROM ANIMAL WHERE CODIGO_RACA IN (SELECT CODIGO_RACA FROM RACA WHERE DESCRICAO_RACA = 'BEAGLE'))
UNION
(SELECT * FROM ANIMAL WHERE CODIGO_ANIMAL IN (SELECT CODIGO_ANIMAL FROM ANIMAL_SERVICO WHERE CODIGO_SERVICO IN (SELECT CODIGO_SERVICO FROM SERVICO WHERE DESCRICAO_SERVICO = 'BANHO/TOSA')))


(SELECT NOME_ANIMAL FROM ANIMAL, ANIMAL_SERVICO, SERVICO WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_SERVICO.CODIGO_ANIMAL AND ANIMAL_SERVICO.CODIGO_SERVICO = SERVICO.CODIGO_SERVICO AND DESCRICAO_SERVICO = 'VACINAÇÃO')
INTERSECT
(SELECT NOME_ANIMAL FROM ANIMAL, ANIMAL_MEDICAMENTO, MEDICAMENTO WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_MEDICAMENTO.CODIGO_ANIMAL AND MEDICAMENTO.CODIGO_MEDICAMENTO = ANIMAL_MEDICAMENTO.CODIGO_MEDICAMENTO AND DESCRICAO_MEDICAMENTO = 'ZATSIM')

SELECT CODIGO_ANIMAL, (SELECT SUM(VALUNIT_SERVICO * QTDE_SERVICO) FROM SERVICO, ANIMAL_SERVICO WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_SERVICO.CODIGO_ANIMAL) FROM ANIMAL 
WHERE (SELECT SUM(VALUNIT_SERVICO * QTDE_SERVICO) FROM SERVICO, ANIMAL_SERVICO WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_SERVICO.CODIGO_ANIMAL) > (SELECT SUM(VALUNIT_SERVICO * QTDE_SERVICO) FROM SERVICO, ANIMAL_SERVICO WHERE ANIMAL.CODIGO_ANIMAL = ANIMAL_SERVICO.CODIGO_ANIMAL AND CODIGO_ANIMAL = 'AN001');

SELECT MAX(VALUNIT_SERVICO) AS VAL_SERVICO FROM SERVICO;

SELECT NOME_DONO, (SELECT COUNT(*) FROM ANIMAL WHERE ANIMAL.CODIGO_DONO = DONO.CODIGO_DONO) FROM DONO; 

--

--

SELECT NOME_ANIMAL FROM ANIMAL WHERE CODIGO_ANIMAL IN (SELECT CODIGO_ANIMAL FROM ANIMAL_SERVICO) AND CODIGO_ANIMAL NOT IN (SELECT CODIGO_ANIMAL FROM ANIMAL_MEDICAMENTO);

SELECT * FROM ANIMAL WHERE CODIGO_RACA IN (SELECT CODIGO_RACA FROM RACA WHERE PAIS_RACA IN (SELECT PAIS_RACA FROM RACA WHERE DESCRICAO_RACA = 'BULDOGUE'));

SELECT DESCRICAO_RACA, PAIS_RACA, COUNT(*) FROM ANIMAL, RACA WHERE ANIMAL.CODIGO_RACA = RACA.CODIGO_RACA
GROUP BY DESCRICAO_RACA, RACA.PAIS_RACA;

SELECT CODIGO_MEDICAMENTO FROM MEDICAMENTO WHERE CODIGO_MEDICAMENTO IN (SELECT CODIGO_MEDICAMENTO FROM ANIMAL_MEDICAMENTO WHERE CODIGO_VETERINARIO = 'VE005');